### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tinmarino**
Dev branch with async and 10 languages. As discussed in #41

I reverted #32  then could merge then reverted the revert so that this branch is 100% above master and a rebase is possible.

Please do not squash, in case of bug, the history of refaction can help.

### CODE REVIEW

**Comment by tinmarino** [comment]
There is a continous testing with travis [See last test](https://travis-ci.com/github/tinmarino/jupyter-vim/builds/198643054)

Please add [this organisation to travis](https://docs.travis-ci.com/user/tutorial/) to get the build auto. I think you must have the orga credentials

**Comment by wmvanvliet** [comment]
Awesome @tinmarino! Ik, I propose thst @broesler and myself test this branch and if we don't find any obvious bugs, merge this. Maybe we'll find things to clean up over time, but we can make new PRs if/when that happens.

😍 Unit tests!

**Comment by wmvanvliet** [comment]
Why are all the commands changed? For example `JupyterConnect` is now `JConnect`? This strikes me as an unnecassary breaking change

**Comment by tinmarino** [comment]
This is @broesler change as Vimmers do not like to type. I like it.

**Comment by wmvanvliet** [comment]
Other than that, I absolutely love this branch.

**Comment by wmvanvliet** [comment]
I like it better too. However, I do not really like introducing breaking backwards compatibility. Is it worth it in this case?

**Comment by wmvanvliet** [comment]
Perhaps yes, because so much changes with this PR. If we're going to do it, this may be the best time

**Comment by tinmarino** [comment]
I am not sure JupyterConnect -> JConnect

+ Short at begining
- May lead to a name conflict and user could alias it anyway
+ But user will never alias it (with the coresponding completion

= I personally am in favor as I have no namespace conflict

**Comment by tinmarino** [comment]
To resolve the conflict, the best is to revert the last PR conflicting, apply this PR and then restore the changes __By hand__.

I can do it now if you wish, that is why I wanted to merge soon as other PRs are towards the master branch (which is not helping my workflow on dev).

**Comment by wmvanvliet** [comment]
Ok, let's revert these name changes for now. After that, I'm +1 for merge for this.

**Comment by tinmarino** [comment]
I was speaking about the merge conflict ...
So I am doing both changes JConnect -> JupyterConnect and Resolve merge conflict

**Comment by tinmarino** [comment]
@wmvanvliet Conflict has been fixed by reverting #44 <= useless now
JConnect -> JupyterConnect, same for its bothers

**Comment by tinmarino** [comment]
@wmvanvliet @broesler shouldn't we ask contributors to make PR on the dev branch: to avoid the same type of problem and to avoid @wmvanvliet as a single point of failure at every PR?

So that we can relax, accept PR on dev, and once a year update the master.
That is what we are doing on [vimwiki](https://github.com/vimwiki/vimwiki) and it works great: I could create the Vader test quietly in dev while some other were improving the table behavior and end-users did not feel any perturbation

**Review by wmvanvliet — APPROVED** [review]

**Comment by wmvanvliet** [comment]
Go ahead and press the shiny green button!

**Comment by wmvanvliet** [comment]
I'm in favor of submitting PRs to the dev branch, seeing as every commit to master is an official release.

**Comment by wmvanvliet** [comment]
Great work @tinmarino! This merge marks a leap forward for the plugin. Sorry it took so long to merge.

**Pull request merged**
