### PR TITLE
Code refraction && More languages supported && Asynchronous connection && Choose kernel name

### LINKED ISSUE #5: Allow choosing which kernel to connect to
I love this plugin as a replacement for Jupyter notebooks!

I frequently work with multiple kernels simultaneously, which used to be encapsulated in distinct notebooks. It would be fantastic and I would recommend this plugin more widely at my firm if it easily supported multiple kernels (e.g. on `JupyterConnect`, if multiple connection files are found, show a list of kernel UUIDs/pids and allow the user to select which one to connect to).

I realize this might be tricky since `jupyter_client.connect.find_connection_file` returns the most recent match, but maybe this plugin could just search the Jupyter runtime dir directly?

### PR DESCRIPTION
**Pull request by tinmarino**
I'd be glad to fix some issues (#21) but prefer to keep one branch. So review is very welcome.

This also fixes #5, and improves my other PR #14.

Once merged (if merged). I'll also add some non regression automatic travis test.

[v0.0?]
* Refactor interface: one object <- one global
	`:py3 print(_jupyter_session.client.check_connection())`
* Kernel support: `Rust`, `Raku`

[v0.01]
* Kernel support: `Bash`, `Cpp`, `Java`, `Javascript`, `Perl`, `Ruby`
* Asynchronous `:JupyterConnect`
* Refactor interface: one global to rule them all
	`:py3 print(jupyter_vim.SI.client.check_connection())`
* `:JupyterConnect` -> autocompletion
* `:jupyterCd` -> echo cwd
* Parse message more tolerantly and resiliently
* Add github wiki

### CODE REVIEW

**Comment by wmvanvliet** [comment]
Awesome @tinmarino! Thanks for opening a PR.

Sorry I am so slow in reviewing anything lately. Really great to have support for multiple languages. I'll try to take a careful look soon.

In the meanwhile, what was the reasoning behind needing an asynchronous `JupyterConnect`? For me, the command was always fast and not done frequently enough to warrant adding async complexity for, but I'm guessing you have other use cases than mine.

**Comment by tinmarino** [comment]
> What was the reasoning behind needing an asynchronous JupyterConnect?

The advantage is no freeze at all.
Also there is never (as I tested) a stack trace. Just some (Cannot Connect) message.

If it doesn't find any kernel to connect with, this freezed the UI.
I also made the wait for message async (in debug monitor for example) asynchronous so one never wait.
The Vim api is synchronous and is called with a python `Queue` and vim `timers` so there is no strange asynchronicity bugs.  I tested that with "fuzzing scripts".

**Comment by tinmarino** [comment]
I admit there is (800) more lines

Explained with

1. More languages supported
2. Comment and sparse code
3. Async (I really find that smoother but easier to remove than to add in the first case).
4. No rely on global variables -> In the future, different buffers can have different sessions (even if I find that useless, maybe someone will want that).

**Comment by wmvanvliet** [comment]
> If it doesn't find any kernel to connect with, this freezed the UI.

Ah yes. Good point!

**Comment by roachsinai** [comment]
Wow, there are 117 commits!!!

**Comment by broesler** [comment]
@tinmarino it looks like you've done great work here, but this is a massive amount of changes to review in a single merge. It also looks like there is some development code hanging around that we don't just want to throw into `master`.

Do you mind submitting each of these features as a separate pull request? (_i.e._ language support, async connection, choosing kernel name). That will make it faster to review as well since you already know the commit history and we don't.

**Comment by tinmarino** [comment]
I'll try, the problem is that I started refactoring the code in classes. So I'll have to make that PR first, the other will rely on it.

**Comment by tinmarino** [comment]
Well actually, I can't (It'd take me one day): __Languages__ and __Threads__ depends on __class refaction__ which increases the indent. So almost every lines get rewritten, and sometime moved from file to file.
The idea, is to compare the before and after as I worked 1 week alone.
It is true that many commits in this PR are only fixes of my own errors ...

That is why I am creating another PR #23 with only few dangerous commits. As I created more modules, I add them first as helper. Then change the existing code, only in 
20a752a  and 4e1928a, At least the last commit works. And you have only those 2 to review.

**Pull request closed without merging**
